model:
  - GraphSAGE
device:
  - gpu
batch_size:
  - 32
learning_rate:
  - 0.0001
  # - 0.01
  - 0.001
l2:
  - 0.
classifier_epochs:
  - 200
optimizer:
  - Adam
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
gradient_clipping:
  - null
early_stopper:
  -
    class: Patience
    args:
      patience: 100
      use_loss: False
shuffle:
  - True
dim_embedding:
  # - 16
  - 32
  - 64
num_layers:
  - 3
  # - 5
aggregation:
  # - mean
  - sum
additional_features:
  - tri_cycle,index_id

# Followings are all additional feature names:
#                "degree":node_degree_feature,
    #             "allone":node_allone_feature,
    #             "index_id":node_index_feature,
    #             "guassian":node_gaussian_feature,
    #             "tri_cycle":node_tri_cycles_feature,
    #             "kadj": node_k_adj_feature,
    #             "rand_id":node_random_id_feature
    #             }
    #     self.registered = []

    # def register(self, arg_str:str=None):
        # arg_str format: name@key:value;key:value....