model:
  - MolecularFingerprint
device:
  - cuda:0
batch_size:
  - 32
hidden_units:
  - 64
  - 128
learning_rate:
  - 0.0001
  - 0.001
l2:
  - 0.001
classifier_epochs:
  - 200
optimizer:
  - Adam
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
gradient_clipping:
  - null
early_stopper:
  -
    class: Patience
    args:
      patience: 500
      use_loss: False
  -
    class: Patience
    args:
      patience: 500
      use_loss: True
shuffle:
  - True
additional_graph_features:
  - stats_degree