model:
  - GIN
device:
  - cuda:0
batch_size:
  - 32
  # - 128
learning_rate:
  - 0.001
classifier_epochs:
  - 500
hidden_units:  # Note: GIN add a first layer that simply adds up all node features
  - [64, 62, 32]
optimizer:
  - Adam
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
train_eps:
  # - true
  - false
l2:
  - 0.
aggregation:
  # - mean
  - sum
gradient_clipping:
  - null
dropout:
  - 0.5
early_stopper:
  -
    class: Patience
    args:
      patience: 500
      use_loss: False
shuffle:
  - True
resume:
  - False

additional_features:
  - use_random,use_eigen
  # degree
  # NOTE: use_xxx is created by prepareDataset. xxx without use_ is created by node_feature_register
# print different features.

node_attribute:
  - True