model:
  - MolecularFingerprint
device:
  - cuda:0
batch_size:
  - 32
hidden_units:
  - 128
learning_rate:
  - 0.005
  - 0.01
l2:
  - 0.
classifier_epochs:
  - 500
optimizer:
  # - Adam
  - SGD
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
gradient_clipping:
  - null
early_stopper:
#   -
#     class: Patience
#     args:
#       patience: 500
#       use_loss: False
  -
    class: Patience
    args:
      patience: 500
      use_loss: True
shuffle:
  - True
  
additional_graph_features:
  - stats_degree
  # - avg_degree